PythonWeb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from unicodedata import name
from xml.dom.minidom import Document
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('Test/', views.Test),
    #path('postDocGia/', views.postDocGia),
    
    path('ListDocGia/', views.ListDocGia, name= "ListDocGia"),
    path('SaveDocGia/', views.ThemDocGia.as_view(), name= "saveDG"),
    path('get/ajax/validate/nickname', views.checkNickName, name = "validate_nickname"),
    path('FindDocGia/',views.TimDocGia.as_view(),name="find_dg"),
    path('DeleteDocGia/',views.XoaDocGia.as_view(),name="xoaDG_index"),
    path('delete_DG/<int:id>',views.delete_docgia, name='deleteDG'),
    path('AlterDocGia/',views.SuaDocGia.as_view(),name='alterDG'),
    path('Sua_DG/<int:id>',views.Sua_DG, name='Sua_DG'),
    path('AddSach/', views.AddSach.as_view(),name= "saveSach"),
    path('get/ajax/validate/sach', views.checkSach, name = "validate_sach"),
    path('get/ajax/validate/sach2', views.checkSach2, name = "validate_sach2"),
    path('ListSach/', views.ListSach,name= "ListSach"),
    path('SachCNTT/', views.SachCNTT,name= "SachCNTT"),
    path('SachATTT/', views.SachATTT,name= "SachATTT"),
    path('SachDC/', views.SachDC,name= "SachDC"),
    path('SachTK/', views.SachTK,name= "SachTK"),
    path('SachGT/', views.SachGT,name= "SachGT"),
    path('SachDTVT/', views.SachDTVT,name= "SachDTVT"),
    path('FindSach/',views.FindSach.as_view(),name= "FindSach"),
    path('FindSachByName/',views.FindSachByName,name= "FindSachByName"),
    path('DeleteSach/',views.XoaSach.as_view(),name= "XoaSach"),
    path('AlterSach/',views.SuaSach.as_view(),name='alterSach'),
    path('delete_S/<int:id>',views.delete_sach, name='deleteSach'),
    path('inf_sach/<int:id>',views.infor_sach, name='infSach'),
    path('get/ajax/validate/pms', views.checkPMS, name = "validate_pms"),
    path('ListPMS/', views.ListPMS,name = "ListPMS"),
    path('ListPMS2/', views.ListPMS2,name = "ListPMS2"),
    path('ListPMS_DG/', views.ListPMS_DG,name = "ListPMS_DG"),
    path('ListPMS_DG2/', views.ListPMS_DG2,name = "ListPMS_DG2"),
    path('TraSach/', views.TraSach.as_view(),name='traSach'),
    path('timTraSach/', views.timTraSach.as_view(),name='timTraSach'),
    path('TraSach_DG/', views.TraSach_DG.as_view(),name='traSach_DG'),
    path('AddPhieuMuonSach/',views.AddPhieuMuonSach.as_view(),name="AddPhieuMuonSach"),
    path('AddPMS_DG/',views.AddPMS_DG.as_view(),name="AddPMS_DG"),
    path('delete_PMS/<int:id>',views.delete_PMS, name='delete_PMS'),
    path('TraSach_id/<int:id>',views.TraSach_id, name='TraSach_id'),
    path('XoaPMS/',views.XoaPMS.as_view(),name="XoaPMS"),
    path('Register/',views.registerUser.as_view(),name= "registerUser"),
    path('get/ajax/validate/user', views.checkUser, name = "validate_user"),
    path('Login/',views.loginUser.as_view(),name= "loginUser"),
    path('Logout/',views.logoutUser,name= "logoutUser"),
    path('ChangePassword/',views.changePassword.as_view(),name= "changePassword"),
    path('Trangchu/',views.mainlib,name= "mainlib"),
   
    
] 
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from ast import mod
from random import choices
from django.db import models
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User

# Create your models here.
class DocGia(models.Model):
    maDG = models.CharField(max_length=50)
    tenDG = models.CharField(max_length=100)
    ngaySinh = models.DateField()
    ngaySinh = models.DateField(null=True)
    #time = models.TimeField(null=True)
    sex_choice = (("Nữ", "Nữ"),("Nam","Nam"),('Không xác định','Không xác định'))
    #char_choice = (('Gay','Gay'),('Ngáo','Ngáo'),('Đbrrr','Đbrrr'))
    gioiTinh = models.CharField(choices = sex_choice,max_length=50,default='Nữ')
    #gioiTinh = MultiSelectField(choices =sex_choice,default='Nữ' )
    SDT = models.CharField(max_length=100)
    diaChi = models.CharField(max_length=100)
    def __str__(self):
        return self.tenDG
    
class Sach(models.Model):
    maSach = models.CharField(max_length=50 )
    tenSach = models.CharField(max_length=100)
    loaiSach = models.CharField(max_length=50)
    tenTG = models.CharField(max_length=100)
    nhaXB = models.CharField(max_length=100)
    namXB = models.IntegerField(blank= True)
    trangThaiSach = models.BooleanField(default=True)
    biaSach = models.ImageField(upload_to='images',default = None,null = True)
    def __str__(self):
        return self.maSach
class TaiKhoan(models.Model):
    tK = models.CharField(max_length=50)
    mk = models.CharField(max_length=50)
    
    
class MuonTraSach(models.Model):
    maDG = models.CharField(max_length=100)
    maSach = models.CharField(max_length=100)
    ngayMuon = models.DateField()
    ngayHenTra = models.DateField()
    ngayTra = models.DateField(blank= True,null=True)
    trangThai = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,null=True,on_delete=models.CASCADE)

home/views.py
from asyncio.windows_events import NULL
from collections import UserList
from datetime import date, datetime


from pickle import FALSE, TRUE
from urllib import response
from wsgiref.handlers import format_date_time
from django import views
import django
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import JsonResponse
from django.urls import reverse, reverse_lazy
from requests import request
from rest_framework.parsers import JSONParser 
from rest_framework import status
from rest_framework.views import APIView
from django.core import serializers
from home.models import DocGia, Sach, TaiKhoan, MuonTraSach
from home.serializers import DocGiaSerializers,MuonTraSachSerializers
from home.form import MuonTraSachForm, NhapDocGiaForm,NhapSachForm,RegisterForm,LoginForm,PasswordChangingForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

from rest_framework.decorators import api_view, renderer_classes
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import ensure_csrf_cookie

from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate,login,logout,load_backend

#
from django.views import View
import pymongo
from django.conf import settings
my_client = pymongo.MongoClient('mongodb://localhost:27017')
dblist = my_client.list_database_names()
pythonweb = my_client['PythonWeb']
docgia = pythonweb['home_docgia']
# Create your views here.
import logging
logger = logging.getLogger(__name__)

from home.decorator import admin_only, role_required,admin_only2
from django.utils.decorators import method_decorator      

# Doc Gia API-------------------------------------------------------------------------------------------------------------------------------
# Hiển thị danh sách đọc giả
@login_required(login_url = 'loginUser')
@admin_only
def ListDocGia(request):   
        if request.method == 'GET':
         docgia = DocGia.objects.all().values()
        return render(request, "home/DetailDocGia.html", {'ds' : docgia})
# Thêm đọc giả

class ThemDocGia(LoginRequiredMixin,UserPassesTestMixin,View):
 login_url = 'loginUser'
         
 def get(self, request):
        form = NhapDocGiaForm()
        return render(request, "home/FormAddDocGia.html",{'form':form})
 def post(self, request):
  if request.is_ajax and request.method == "POST":
        docgia_data =  NhapDocGiaForm(request.POST)
        if docgia_data.is_valid():          
                docgia_data.save()
                return JsonResponse({"valid":False}, status=200)    
        return JsonResponse({"error": docgia_data.errors}, status=400)
 def test_func(self):
        return self.request.user.is_superuser
def checkNickName(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        maDG = request.GET.get("maDG", None)
        # check for the nick name in the database.
        if DocGia.objects.filter(maDG = maDG ).exists():
            # if nick_name found return not valid new friend
            return JsonResponse({"valid":False}, status = 200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid":True}, status = 200)

    return JsonResponse({}, status = 400)        
                

def __str__(self):
        pass




'''
@csrf_exempt
def postDocGia(request):
        if request.method == 'POST':
            docgia_data = JSONParser().parse(request)
            docgia_serializer = DocGiaSerializers(data=docgia_data)
            if docgia_serializer.is_valid():
                docgia_serializer.save()
                return JsonResponse(docgia_serializer.data, status=status.HTTP_201_CREATED) 
        return JsonResponse(docgia_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
'''

'''def Test(request):
 if request.method == 'POST':
        FindmaDG = request.POST.get('maDG')   
        FindDGbyName = docgia.find_one({"maDG": FindmaDG})
 return render(request,"home/DetailOneDocGia.html", {'dg' : FindDGbyName})
 
if request.method == "POST":
        orders = Order()
        orders.data = request.POST.get("data")
        orders.time = request.POST.get("time")
        st = request.POST.get("status")
        if st == 'on':
                st = True
        else:
                st = False
        orders.status = st
 '''
# Tìm đọc giả
class TimDocGia(LoginRequiredMixin,UserPassesTestMixin,View):
 login_url = 'loginUser'
 def get(self, request): 
        form = NhapDocGiaForm()
        return render(request, "home/FormTimDocGia.html",{'form':form})
 def post(self, request):
      if request.is_ajax and request.method == "POST":
        # get the nick name from the client side.
        maDG = request.POST.get("maDG", None)
        # check for the nick name in the database.
        if DocGia.objects.filter(maDG = maDG).exists():
            instance = DocGia.objects.get(maDG = maDG)    
            ser_instance = serializers.serialize('json', [ instance, ])
            return JsonResponse({"valid":True,"instance": ser_instance}, status=200)    
        else:
         return JsonResponse({"valid":False}, status = 200)
 def test_func(self):
        return self.request.user.is_superuser  
 

# Xóa đọc giả
class XoaDocGia(LoginRequiredMixin,UserPassesTestMixin,View):
 login_url = 'loginUser'
 def get(self, request): 
        form = NhapDocGiaForm()
        docgia = DocGia.objects.all().values()
        return render(request, "home/FormXoaDocGia.html",{'form':form,'ds' : docgia})

 def post(self, request):
        FindmaDG = request.POST.get('maDG')
        try:
                FindDGbyName = DocGia.objects.get(maDG = FindmaDG)          
        except:
                return HttpResponse("Không tìm thấy đọc giả")
        
        if FindDGbyName:
               FindDGbyName.delete()
               return HttpResponseRedirect(reverse('xoaDG_index')) 
 def test_func(self):
        return self.request.user.is_superuser  
# Xóa đọc giả dùng danh sách
@login_required(login_url = 'loginUser')
@admin_only
def delete_docgia(request,id): 
 if request.is_ajax and request.method == "GET":
        docgia_data = DocGia.objects.get(id=id)        
        docgia_data.delete() 
        return JsonResponse({"message":'success'}, status=200)
 return JsonResponse({"message":'Wrong route'}, status=200)
# Sửa thông tin đọc giả
@login_required(login_url = 'loginUser')
@admin_only
def Sua_DG(request,id):
        data = DocGia.objects.get(id=id)
        return render(request, "home/FormSuaDocGia.html",{'data':data})
class SuaDocGia(LoginRequiredMixin,UserPassesTestMixin,View):
 login_url = 'loginUser'
 def get(self, request):
        form = DocGia.objects.all()
        return render(request, "home/ListSua_DG.html",{'ds':form})

 def post(self, request):
       if request.is_ajax and request.method == "POST":
        # get the nick name from the client side.
        maDG = request.POST.get("maDG", None)
        tenDG = request.POST.get("tenDG", None)
        ngaySinh = request.POST.get("ngaySinh", None)
        gioiTinh = request.POST.get("gioiTinh", None)
        SDT = request.POST.get("SDT", None)
        diaChi = request.POST.get("diaChi", None)        
        if DocGia.objects.filter(maDG = maDG).exists():
                docgia = DocGia.objects.get(maDG = maDG)
                
                if tenDG.strip():
                 docgia.tenDG = tenDG
                if ngaySinh.strip():
                 docgia.ngaySinh = ngaySinh
                if gioiTinh.strip():
                 docgia.gioiTinh = gioiTinh
                if SDT.strip():
                 docgia.SDT = SDT
                if diaChi.strip():
                 docgia.diaChi = diaChi
                 
                docgia.save()
                return JsonResponse({"valid":True}, status=200)  
        else:
                return JsonResponse({"valid":False}, status = 200)  
 def test_func(self):
        return self.request.user.is_superuser 
                
#Sách API----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#check Sach:

def checkSach(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        maSach = request.GET.get("maSach", None)
        # check for the nick name in the database.
        if Sach.objects.filter(maSach = maSach ).exists():
            # if nick_name found return not valid new friend
            return JsonResponse({"valid":False}, status = 200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid":True}, status = 200)

    return JsonResponse({}, status = 400)   
def checkSach2(request):
    if request.is_ajax and request.method == "POST":
        maSach = request.POST.get("maSach", None)
        if Sach.objects.filter(maSach = maSach ).exists():
            instance = Sach.objects.get(maSach = maSach)
            if instance.trangThaiSach ==True: 
                    return JsonResponse({"valid":True, "mess": 1}, status=200)  
            return JsonResponse({"valid":True}, status=200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid":False}, status = 200)

    return JsonResponse({}, status = 400)     
# Danh sách sách:
@login_required(login_url = 'loginUser')
def infor_sach(request,id):
         sach_data = Sach.objects.get(id = id)

home/templates/home/DetailOneDocGia.html
{% extends 'home/base.html' %}

{% block content %} 
<h1>Danh Sach Doc Gia</h1>
<ul>
    {% if dg%}
         <li style="color:red;"> {{dg.maDG}} | {{dg.tenDG}} | {{dg.ngaySinh |date:"d-m-Y"}} | {{dg.SDT}}| {{dg.diaChi}} </li>  
    {% else %}
        <h3 style="color:red;">Không có dữ liệu nào</h3>
    {% endif %}
</ul>  
 {% endblock %}

home/templates/home/DetailPMS2.html
{% extends 'home/base_PMS.html' %}

{% block content %} 
<h2>Danh Sách Phiếu Mượn Sách</h2><br>
<table border="1" class="analytics_table">
    {% if ds%}
    <thead>
        <tr>
            <th>Mã đọc giả</th>
            <th>Mã Sách</th>
            <th>Ngày mượn</th>
            <th>Ngày hẹn trả </th>
            <th>Ngày trả</th>
            <th>Trạng thái</th>
        </tr>

    </thead>
            
    <tbody>
        {% for x in ds%}
        <tr>
            <td>{{x.maDG}} </td>
            <td>{{x.maSach}}</td>
            <td>{{x.ngayMuon|date:"d-m-Y"}}</td>
            <td>{{x.ngayHenTra|date:"d-m-Y"}}</td>
            <td>{{x.ngayTra|date:"d-m-Y"}}</td>
            {% if x.trangThai %}
                    <td>Đã hoàn thành</td> 
            {% else %}
                    <td>Chưa hoàn thành</td>
                    
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    {% else %}
        <h3>Không có dữ liệu nào</h3>
    {% endif %}
</table>
        
 {% endblock %}

home/templates/home/FormSuaSach.html
{% extends 'home/base_bookManager.html' %}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
{% block content %} 
<form action="/home/AlterSach/" method="post" id="sach-form">
    {% csrf_token %}
    <h1>Cập nhật thông tin sách</h1>
    <label for="">Nhập mã sách cần cập nhật</label><br><input type="text" name="maSach" maxlength="50" required id="id_maSach"><br>
    <h2>Cập nhật các trường thông tin sách bạn muốn thay đổi</h2>
    <label for="">Nhập tên sách</label><br>  <input type="text" name="tenSach" maxlength="100"  id="id_tenSach"><br>
    
    <label for="">Nhập loại sách</label><br><input type="text" name="loaiSach" maxlength="50" id="id_loaiSach"><br>

    <label for="">Nhập tác giả</label><br><input type="text" name="tenTG" maxlength="100" id="id_tenTG"><br>

    <label for="">Nhập nhà xuất bản</label><br><input type="text" name="nhaXB" maxlength="100"  id="id_nhaXB"><br>

    <label for="">Nhập năm xuất bản</label><br><input type="number" name="namXB" id="id_namXB"><br>

    <label for="">Trạng thái sách </label><br><select style="width: 180px;" name="trangThaiSach" id="id_trangThaiSach">
        <option value="" selected disabled hidden>Chọn Trạng Thái Sách</option>
        <option value="0">Có thể mượn</option>
      
        <option value="1">Đã được mượn</option>
      
        
      
      </select><br>

      <label for="">Cập nhật hình ảnh sách</label><br><input type="file" name="biaSach" accept="image/*" id="id_biaSach"><br>
      <br>
    <input class="btn btn-primary" type="submit" name="dangki" value="Cập nhật">
</form>
<br> 
{% endblock %}
{% block javascript %}

<script>

     $("#sach-form").submit(function (e) {
    // preventing from page reload and default actions
    e.preventDefault(); 
    if (window.FormData) {
        formData = new FormData();
        formData.append('maSach',$("#id_maSach").val());
        formData.append('tenSach',$("#id_tenSach").val());
        formData.append('loaiSach',$("#id_loaiSach").val());
        formData.append('tenTG',$("#id_tenTG").val());
        formData.append('nhaXB',$("#id_nhaXB").val());
        formData.append('namXB',$("#id_namXB").val());
        formData.append('trangThaiSach',$("#id_trangThaiSach").val());
        formData.append( 'csrfmiddlewaretoken' , $('input[name = csrfmiddlewaretoken]').val());
        formData.append('biaSach', $('input[type=file]')[0].files[0]);
    }
    $.ajax({
        type: 'POST',
        url: "{% url 'alterSach' %}",
        data: formData , 
        processData: false,
        contentType: false,

        success: function (response) {
            if(!response["valid"]){
                alert("Mã sách bạn nhập không tồn tại");
            }
            else {
                alert("Cập nhật thông tin sách thành công");
                window.location.href= "{% url 'ListSach' %}";
            }
            
        },
        error: function (response) {
            // alert the error if any error occured
            alert(response["responseJSON"]["error"]);
            
        }
    })
}) 
$("#id_maSach").focusout(function (e) {
    e.preventDefault();
    // get the nickname
    var maSach = $(this).val();
    // GET AJAX request
    $.ajax({
        type: 'GET',
        url: "{% url 'validate_sach' %}",
        data: {"maSach": maSach },
        success: function (response) {
            // if not valid user, alert the user
            if(response["valid"]){
                alert("Mã sách bạn nhập không tồn tại");
                
            }
        },
        error: function (response) {
            console.log(response)
        }
    })
})

</script>
{% endblock %}

home/templates/home/FormTraSach.html
{% extends 'home/base_PMS.html' %}

{% block content %} 
<!--
<script>
    function formatDate()
    {
        const options = { day: "numeric", month: "long", year: "numeric" };
        date_collection = document.getElementsByClassName('date');
        for(var i = 0; i< date_collection.length; i++)
        {
            var datetime = new Date(Date.parse(date_collection[i].innerHTML));
            alert(datetime);
            const americanDate = new Intl.DateTimeFormat("en-US", options).format(datetime);
            date_collection[i].innerText = americanDate;
            date_collection[i].setAttribute("time",datetime);
        }
    }
    </script>
-->
<h1>Thông Tin Phiếu Mượn</h1><br>
<h6>Mã đọc giả:  <p style="display: inline;" name="maDG" id="id_maDG">{{data.maDG}}</p></h6>
<h6>Mã sách:  <p style="display: inline;" name="maSach" id="id_maSach">{{data.maSach}}</p></h6>
<h6>Ngày mượn sách:  <p style="display: inline;" name="ngayMuon" id="id_ngayMuon">{{data.ngayMuon|date:"d-m-Y"}}</p></h6>
<h6>Ngày hẹn trả:  <p style="display: inline;" name="ngayHenTra" id="id_ngayHenTra">{{data.ngayHenTra|date:"d-m-Y"}}</p></h6>


<form id="ts_form" action="/home/TraSach/" method="post">
    {% csrf_token %}
    
    <h6><label for="">Nhập ngày trả</label></h6><input type="date" name="ngayTra" class="vDateField" style="font-family: SANS-SERIF;
    font-size: x-lrge;" required id="id_ngayTra">
    <br><br>
    <input class="btn btn-primary" type="submit" name="dangki" value="Đăng Kí Trả Sách">
    <br><br>
   
</form>

{% endblock %}
{% block javascript %}
<script>
$("#ts_form").submit(function (e) {
    // preventing from page reload and default actions
    e.preventDefault(); 
    $.ajax({
        type: 'POST',
        url: "{% url 'traSach' %}",
        data: {
            "maDG": $("#id_maDG").text(),
            "maSach":$("#id_maSach").text(),
            "ngayTra" : $("#id_ngayTra").val(),
             csrfmiddlewaretoken : $('input[name = csrfmiddlewaretoken]').val(),

        },
        success: function (response) {
            // on successfull creating object
            if(response["valid"]){
                if(response.mess == 1){
                    alert("Ngày trả bạn nhập không hợp lệ");
                }
                else if(response.mess == 2){
                    alert("Trả sách muộn!!");
                    alert("Đăng kí trả sách thành công");
                     
                   
                }
                else {
                    alert("Đăng kí trả sách thành công");
                    
                    
                }
            }
            else{
                alert("Không tìm thấy phiếu mượn sách (Kiểm tra lại mã sách hoặc mã sinh viên)");
            }
            
        },
        error: function (response) {
            // alert the error if any error occured
            alert(response["error"]);
        }
    })
})
</script>
{% endblock %}

home/templates/home/FormTraSach_DG.html
{% extends 'home/base_PMS2.html' %}

{% block content %} 
<!--
<script>
    function formatDate()
    {
        const options = { day: "numeric", month: "long", year: "numeric" };
        date_collection = document.getElementsByClassName('date');
        for(var i = 0; i< date_collection.length; i++)
        {
            var datetime = new Date(Date.parse(date_collection[i].innerHTML));
            alert(datetime);
            const americanDate = new Intl.DateTimeFormat("en-US", options).format(datetime);
            date_collection[i].innerText = americanDate;
            date_collection[i].setAttribute("time",datetime);
        }
    }
    </script>
-->
<h2>Đăng Kí Trả Sách</h2>

<form id="ts_form" action="/home/TraSach/" method="post">
    {% csrf_token %}
    
    
    <label for="">Nhập mã đọc giả</label><br>{{form.maDG}}<br>

    <label for="">Nhập mã sách</label><br> {{form.maSach}}<br>

    <label for="">Nhập ngày trả</label><br>{{form.ngayTra}}
    
    <br><br>
    <input class="btn btn-primary" type="submit" name="dangki" value="Đăng Kí Trả Sách">
    <br><br>
   
</form>
<h2>Danh Sách Phiếu Mượn Sách</h2><br>
<table border="1" class="analytics_table">
    {% if ds%}
    <thead>
        <tr>
            <th>Mã đọc giả</th>
            <th>Mã Sách</th>
            <th>Ngày mượn</th>
            <th>Ngày hẹn trả </th>
            <th>Ngày trả</th>
            <th>Trạng thái</th>
            
        </tr>

    </thead>
            
    <tbody>
        {% for x in ds%}
        <tr>
            <td>{{x.maDG}} </td>
            <td>{{x.maSach}}</td>
            <td>{{x.ngayMuon|date:"d-m-Y"}}</td>
            <td>{{x.ngayHenTra|date:"d-m-Y"}}</td>
            <td>{{x.ngayTra|date:"d-m-Y"}}</td>
            {% if x.trangThai %}
                    <td>Đã hoàn thành</td> 
            {% else %}
                    <td>Chưa hoàn thành</td>
                    
            {% endif %}
            
        </tr>
        {% endfor %}
    </tbody>
    {% else %}
        <h3>Không có dữ liệu nào</h3>
    {% endif %}
</table>
{% endblock %}
{% block javascript %}
<script>
$("#ts_form").submit(function (e) {
    // preventing from page reload and default actions
    e.preventDefault(); 
    $.ajax({
        type: 'POST',
        url: "{% url 'traSach_DG' %}",
        data: {
            "maDG": $("#id_maDG").val(),
            "maSach":$("#id_maSach").val(),
            "ngayTra" : $("#id_ngayTra").val(),
             csrfmiddlewaretoken : $('input[name = csrfmiddlewaretoken]').val(),

        },
        success: function (response) {
            // on successfull creating object
            if(response["valid"]){
                if(response.mess == 1){
                    alert("Ngày trả bạn nhập không hợp lệ");
                }
                else if(response.mess == 2){
                    alert("Trả sách muộn!!");
                    alert("Đăng kí trả sách thành công");
                    $("#ts_form").trigger('reset');   
                }
                else {
                    alert("Đăng kí trả sách thành công");
                    $("#ts_form").trigger('reset');   
                }
            }
            else{
                alert("Không tìm thấy phiếu mượn sách (Kiểm tra lại mã sách hoặc mã sinh viên)");
            }
            
        },
        error: function (response) {
            // alert the error if any error occured
            alert(response["error"]);
        }
    })
})
</script>
{% endblock %}